# Generated by Django 6.0.4 on 2026-04-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tbl_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream', models.BooleanField(blank=True, null=True)),
                ('downstream', models.BooleanField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('dependency_team_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_dependencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('codebase', models.TextField(blank=True, null=True)),
                ('jira_board', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills_and_tech', models.TextField(blank=True, null=True)),
                ('software_owned_and_evolved', models.TextField(blank=True, null=True)),
                ('versioning', models.TextField(blank=True, null=True)),
                ('agile_practices', models.TextField(blank=True, null=True)),
                ('slack', models.TextField(blank=True, null=True)),
                ('wiki', models.TextField(blank=True, null=True)),
                ('wiki_search_terms', models.TextField(blank=True, null=True)),
                ('daily_standup', models.DateTimeField(blank=True, null=True)),
                ('active_projects', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('sname', models.TextField(blank=True, null=True)),
                ('uname', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('role', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.tbluser')),
            ],
            options={
                'db_table': 'tbl_audit',
                'ordering': ['-datetime'],
            },
        ),
    ]
