# Generated by Django 6.0.4 on 2026-04-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_meeting_location_meeting_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
