# Generated by Django 6.0.4 on 2026-04-27 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('schedule', '0003_meeting_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tblteam'),
        ),
    ]
